# Generated by Django 3.2.9 on 2021-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del estudiante', max_length=20)),
                ('paterno', models.CharField(help_text='apellido paterno', max_length=15)),
                ('materno', models.CharField(help_text='apellido materno', max_length=15)),
                ('ru', models.CharField(help_text='RU del estudiante', max_length=10, unique=True)),
                ('email', models.EmailField(help_text='Correo electronico del estudiante', max_length=190, unique=True)),
                ('ci', models.CharField(help_text='Cedula de identidad del estudiante', max_length=12, unique=True)),
            ],
            options={
                'ordering': ['-paterno', 'materno', 'nombres'],
            },
        ),
    ]
