# Generated by Django 3.2.9 on 2021-12-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreasic', models.CharField(help_text='Nombre de la asignatura', max_length=30)),
                ('sigla', models.CharField(help_text='Sigla de la asignatura', max_length=6)),
                ('horas', models.IntegerField(help_text='Horas de la asignatura')),
                ('semestre', models.IntegerField(help_text='Semestre de la asignatura')),
            ],
            options={
                'ordering': ['nombreasic'],
            },
        ),
    ]
